
services:
  honeypot:
    build: .
    container_name: honeypot_nexus
    ports:
      - "2222:2222"   # SSH
      - "2121:2121"   # FTP
      - "8080:8080"   # HTTP
      - "2323:2323"   # Telnet
      - "4444:4444"   # NC
      - "5050:5050"   # Dashboard API
    volumes:
      - ./honeypot.db:/app/honeypot.db
      - ./honeypot.log:/app/honeypot.log
      - ./honeypot_out.log:/app/honeypot_out.log
    restart: unless-stopped
