#!/usr/bin/env bash
set -euo pipefail

MODE="${1:-docker}"
ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT_DIR"

need_cmd() {
  command -v "$1" >/dev/null 2>&1 || {
    echo "Missing required command: $1" >&2
    exit 1
  }
}

make_secret() {
  python3 - <<'PY'
import secrets
print(secrets.token_urlsafe(32))
PY
}

prompt_value() {
  local label="$1"
  local default="$2"
  local value=""
  if [[ -n "$default" ]]; then
    read -r -p "$label [$default]: " value
    printf '%s' "${value:-$default}"
  else
    read -r -p "$label: " value
    printf '%s' "$value"
  fi
}

prompt_password() {
  local first="" second=""
  while true; do
    read -r -s -p "Dashboard admin password (12+ chars, no defaults): " first
    echo
    read -r -s -p "Confirm dashboard admin password: " second
    echo
    if [[ "$first" != "$second" ]]; then
      echo "Passwords did not match. Try again."
      continue
    fi
    if [[ ${#first} -lt 12 ]]; then
      echo "Password must be at least 12 characters. Try again."
      continue
    fi
    printf '%s' "$first"
    return 0
  done
}

prompt_deploy_config() {
  local bind_host="$1"
  local interactive="0"
  [[ -t 0 && "${HONEYPOT_QUICK_DEPLOY_NON_INTERACTIVE:-0}" != "1" ]] && interactive="1"

  DEPLOY_ADMIN_USER="${HONEYPOT_ADMIN_USER:-admin}"
  DEPLOY_ADMIN_PASS="${HONEYPOT_ADMIN_PASS:-}"
  DEPLOY_PUBLIC_URL="${HONEYPOT_PUBLIC_URL:-http://localhost:${HONEYPOT_DASHBOARD_PORT:-5050}}"
  DEPLOY_ALERTS_ENABLED="${HONEYPOT_ALERTS_ENABLED:-false}"
  DEPLOY_ALERT_MIN_SEVERITY="${HONEYPOT_ALERT_MIN_SEVERITY:-high}"
  DEPLOY_SLACK_WEBHOOK_URL="${SLACK_WEBHOOK_URL:-}"
  DEPLOY_DISCORD_WEBHOOK_URL="${DISCORD_WEBHOOK_URL:-}"
  DEPLOY_TELEGRAM_BOT_TOKEN="${TELEGRAM_BOT_TOKEN:-}"
  DEPLOY_TELEGRAM_CHAT_ID="${TELEGRAM_CHAT_ID:-}"
  DEPLOY_N8N_WEBHOOK_URL="${N8N_WEBHOOK_URL:-}"

  if [[ "$interactive" == "1" ]]; then
    echo "HoneyPot v3 quick deploy setup"
    echo "Enter the private dashboard owner/admin account and public URL/domain for this deployment."
    DEPLOY_ADMIN_USER="$(prompt_value "Dashboard admin username" "$DEPLOY_ADMIN_USER")"
    if [[ -z "$DEPLOY_ADMIN_PASS" ]]; then
      DEPLOY_ADMIN_PASS="$(prompt_password)"
    fi
    DEPLOY_PUBLIC_URL="$(prompt_value "Public dashboard URL/domain" "$DEPLOY_PUBLIC_URL")"
    DEPLOY_ALERTS_ENABLED="$(prompt_value "Enable alert connections now? yes/no" "${DEPLOY_ALERTS_ENABLED}")"
    if [[ "${DEPLOY_ALERTS_ENABLED,,}" =~ ^(1|true|yes|on|y)$ ]]; then
      DEPLOY_ALERT_MIN_SEVERITY="$(prompt_value "Minimum alert severity" "$DEPLOY_ALERT_MIN_SEVERITY")"
      DEPLOY_SLACK_WEBHOOK_URL="$(prompt_value "Slack webhook URL (optional)" "$DEPLOY_SLACK_WEBHOOK_URL")"
      DEPLOY_DISCORD_WEBHOOK_URL="$(prompt_value "Discord webhook URL (optional)" "$DEPLOY_DISCORD_WEBHOOK_URL")"
      DEPLOY_TELEGRAM_BOT_TOKEN="$(prompt_value "Telegram bot token (optional)" "$DEPLOY_TELEGRAM_BOT_TOKEN")"
      DEPLOY_TELEGRAM_CHAT_ID="$(prompt_value "Telegram chat ID (optional)" "$DEPLOY_TELEGRAM_CHAT_ID")"
      DEPLOY_N8N_WEBHOOK_URL="$(prompt_value "n8n webhook URL (optional)" "$DEPLOY_N8N_WEBHOOK_URL")"
    fi
  elif [[ -z "$DEPLOY_ADMIN_PASS" ]]; then
    DEPLOY_ADMIN_PASS="$(make_secret)"
  fi

  python3 setup.py \
    --non-interactive \
    --force \
    --admin-user "$DEPLOY_ADMIN_USER" \
    --admin-pass "$DEPLOY_ADMIN_PASS" \
    --bind-host "$bind_host" \
    --dashboard-port "${HONEYPOT_DASHBOARD_PORT:-5050}" \
    --alerts-enabled "$DEPLOY_ALERTS_ENABLED" \
    --alert-min-severity "$DEPLOY_ALERT_MIN_SEVERITY" \
    --slack-webhook-url "$DEPLOY_SLACK_WEBHOOK_URL" \
    --discord-webhook-url "$DEPLOY_DISCORD_WEBHOOK_URL" \
    --telegram-bot-token "$DEPLOY_TELEGRAM_BOT_TOKEN" \
    --telegram-chat-id "$DEPLOY_TELEGRAM_CHAT_ID" \
    --n8n-webhook-url "$DEPLOY_N8N_WEBHOOK_URL" \
    --public-url "$DEPLOY_PUBLIC_URL"
}

write_credentials_note() {
  local user="$1"
  local pass="$2"
  local public_url="$3"
  umask 077
  cat > .deploy-credentials.txt <<EOF
HoneyPot v3 local deployment credentials
Generated: $(date -u +%Y-%m-%dT%H:%M:%SZ)
Dashboard: ${public_url}
Username: ${user}
Password: ${pass}

Keep this file private. Delete it after saving credentials in your password manager.
EOF
}

create_env() {
  local bind_host="$1"
  local n8n_key="${N8N_ENCRYPTION_KEY:-$(make_secret)}"

  if [[ -f .env && "${FORCE:-0}" != "1" ]]; then
    echo ".env already exists; reusing it. Set FORCE=1 to regenerate."
    return 0
  fi

  prompt_deploy_config "$bind_host"

  umask 077
  cat >> .env <<EOF

# Deployment defaults generated by scripts/quick_deploy.sh
HONEYPOT_DB_PATH=${HONEYPOT_DB_PATH:-/app/data/honeypot.db}
HONEYPOT_INDEXNOW_KEY=${HONEYPOT_INDEXNOW_KEY:-}
N8N_ENCRYPTION_KEY=${n8n_key}
N8N_WEBHOOK_PUBLIC_URL=${N8N_WEBHOOK_PUBLIC_URL:-http://localhost:5678/}
EOF
  chmod 600 .env
  write_credentials_note "$DEPLOY_ADMIN_USER" "$DEPLOY_ADMIN_PASS" "$DEPLOY_PUBLIC_URL"
  echo "Successfully setup HoneyPot v3 quick deploy configuration."
  echo "Credentials saved in: $ROOT_DIR/.deploy-credentials.txt"
}

wait_for_health() {
  local url="${1:-http://127.0.0.1:5050/api/health}"
  for _ in $(seq 1 45); do
    if python3 - "$url" <<'PY' >/dev/null 2>&1
import sys, urllib.request
urllib.request.urlopen(sys.argv[1], timeout=2).read()
PY
    then
      echo "Health check passed: $url"
      return 0
    fi
    sleep 2
  done
  echo "Health check did not pass yet. Check logs with: docker compose logs -f honeypot" >&2
  return 1
}

case "$MODE" in
  docker)
    need_cmd python3
    need_cmd docker
    create_env "0.0.0.0"
    docker compose up -d --build honeypot
    wait_for_health "http://127.0.0.1:5050/api/health" || true
    echo
    echo "HoneyPot v3 is deployed."
    echo "Dashboard: ${DEPLOY_PUBLIC_URL:-http://localhost:5050}"
    echo "Credentials saved in: $ROOT_DIR/.deploy-credentials.txt"
    echo "Logs: docker compose logs -f honeypot"
    ;;
  local)
    need_cmd python3
    create_env "127.0.0.1"
    python3 -m venv .venv
    .venv/bin/python -m pip install --upgrade pip
    .venv/bin/python -m pip install -r requirements.txt
    echo
    echo "Local setup complete. Start with: .venv/bin/python main.py"
    echo "Dashboard: ${DEPLOY_PUBLIC_URL:-http://localhost:5050}"
    echo "Credentials saved in: $ROOT_DIR/.deploy-credentials.txt"
    ;;
  stop)
    need_cmd docker
    docker compose down
    ;;
  status)
    need_cmd docker
    docker compose ps
    ;;
  *)
    cat >&2 <<'EOF'
Usage:
  ./scripts/quick_deploy.sh docker   # fastest Docker deployment; prompts for admin/password/domain in a TTY
  ./scripts/quick_deploy.sh local    # Python virtualenv setup; prompts for admin/password/domain in a TTY
  ./scripts/quick_deploy.sh status   # docker compose status
  ./scripts/quick_deploy.sh stop     # stop Docker deployment

Optional env:
  FORCE=1                                      regenerate .env
  HONEYPOT_QUICK_DEPLOY_NON_INTERACTIVE=1      skip prompts and generate/use env credentials
  HONEYPOT_PUBLIC_URL=https://security.site    public dashboard URL/domain
  HONEYPOT_ADMIN_USER=operator                 dashboard username
  HONEYPOT_ADMIN_PASS=...                      dashboard password
EOF
    exit 2
    ;;
esac
