#!/usr/bin/env bash
set -euo pipefail

MODE="${1:-docker}"
ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT_DIR"

need_cmd() {
  command -v "$1" >/dev/null 2>&1 || {
    echo "Missing required command: $1" >&2
    exit 1
  }
}

make_secret() {
  python3 - <<'PY'
import secrets
print(secrets.token_urlsafe(32))
PY
}

write_credentials_note() {
  local user="$1"
  local pass="$2"
  umask 077
  cat > .deploy-credentials.txt <<EOF
HoneyPot v3 local deployment credentials
Generated: $(date -u +%Y-%m-%dT%H:%M:%SZ)
Dashboard: http://localhost:5050
Username: ${user}
Password: ${pass}

Keep this file private. Delete it after saving credentials in your password manager.
EOF
}

create_env() {
  local bind_host="$1"
  local admin_user="${HONEYPOT_ADMIN_USER:-admin}"
  local admin_pass="${HONEYPOT_ADMIN_PASS:-$(make_secret)}"
  local n8n_key="${N8N_ENCRYPTION_KEY:-$(make_secret)}"
  local public_url="${HONEYPOT_PUBLIC_URL:-http://localhost:5050}"

  if [[ -f .env && "${FORCE:-0}" != "1" ]]; then
    echo ".env already exists; reusing it. Set FORCE=1 to regenerate."
    return 0
  fi

  python3 setup.py \
    --non-interactive \
    --force \
    --admin-user "$admin_user" \
    --admin-pass "$admin_pass" \
    --bind-host "$bind_host" \
    --dashboard-port "${HONEYPOT_DASHBOARD_PORT:-5050}"

  umask 077
  cat >> .env <<EOF

# Deployment defaults generated by scripts/quick_deploy.sh
HONEYPOT_DB_PATH=${HONEYPOT_DB_PATH:-/app/data/honeypot.db}
HONEYPOT_PUBLIC_URL=${public_url}
HONEYPOT_INDEXNOW_KEY=${HONEYPOT_INDEXNOW_KEY:-}
N8N_ENCRYPTION_KEY=${n8n_key}
N8N_WEBHOOK_PUBLIC_URL=${N8N_WEBHOOK_PUBLIC_URL:-http://localhost:5678/}
EOF
  chmod 600 .env
  write_credentials_note "$admin_user" "$admin_pass"
  echo "Created .env and .deploy-credentials.txt with owner-only permissions."
}

wait_for_health() {
  local url="${1:-http://127.0.0.1:5050/api/health}"
  for _ in $(seq 1 45); do
    if python3 - "$url" <<'PY' >/dev/null 2>&1
import sys, urllib.request
urllib.request.urlopen(sys.argv[1], timeout=2).read()
PY
    then
      echo "Health check passed: $url"
      return 0
    fi
    sleep 2
  done
  echo "Health check did not pass yet. Check logs with: docker compose logs -f honeypot" >&2
  return 1
}

case "$MODE" in
  docker)
    need_cmd python3
    need_cmd docker
    create_env "0.0.0.0"
    docker compose up -d --build honeypot
    wait_for_health "http://127.0.0.1:5050/api/health" || true
    echo
    echo "HoneyPot v3 is deployed."
    echo "Dashboard: http://localhost:5050"
    echo "Credentials saved in: $ROOT_DIR/.deploy-credentials.txt"
    echo "Logs: docker compose logs -f honeypot"
    ;;
  local)
    need_cmd python3
    create_env "127.0.0.1"
    python3 -m venv .venv
    .venv/bin/python -m pip install --upgrade pip
    .venv/bin/python -m pip install -r requirements.txt
    echo
    echo "Local setup complete. Start with: .venv/bin/python main.py"
    echo "Dashboard: http://localhost:5050"
    echo "Credentials saved in: $ROOT_DIR/.deploy-credentials.txt"
    ;;
  stop)
    need_cmd docker
    docker compose down
    ;;
  status)
    need_cmd docker
    docker compose ps
    ;;
  *)
    cat >&2 <<'EOF'
Usage:
  ./scripts/quick_deploy.sh docker   # fastest Docker deployment
  ./scripts/quick_deploy.sh local    # Python virtualenv setup
  ./scripts/quick_deploy.sh status   # docker compose status
  ./scripts/quick_deploy.sh stop     # stop Docker deployment

Optional env:
  FORCE=1                         regenerate .env
  HONEYPOT_PUBLIC_URL=https://...  public URL for sitemap/indexing
  HONEYPOT_ADMIN_USER=operator     dashboard username
  HONEYPOT_ADMIN_PASS=...          dashboard password
EOF
    exit 2
    ;;
esac
