input {
  file {
    path => "/var/log/honeypot/honeypot.log"
    start_position => "beginning"
    sincedb_path => "/tmp/logstash-honeypot-sincedb"
  }
}

filter {
  grok {
    match => {
      "message" => [
        "%{TIMESTAMP_ISO8601:timestamp} - \[%{WORD:event_type}\] %{WORD:service}\(%{INT:service_port}\) %{IPORHOST:source_ip}: %{GREEDYDATA:event_message}",
        "%{TIMESTAMP_ISO8601:timestamp} - %{GREEDYDATA:event_message}"
      ]
    }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "honeypot-events-%{+YYYY.MM.dd}"
  }
  stdout { codec => rubydebug }
}
